name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Describe alternatives you've considered

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - API (SportRental.Api)
        - Admin Panel (SportRental.Admin)
        - Client (SportRental.Client)
        - Media Storage (SportRental.MediaStorage)
        - Infrastructure
        - All components
        - Other
    validations:
      required: true

  - type: checkboxes
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature?
      options:
        - label: End users (customers)
        - label: Business owners (rental shops)
        - label: Developers
        - label: System administrators

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with testing
